# [START jenkins_deployment]
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: nalbam/jenkins:latest
        ports:
        - containerPort: 8080
        - containerPort: 50000
        readinessProbe:
          httpGet:
            path: /login
            port: 8080
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 2
          failureThreshold: 5
#        volumeMounts:
#        - mountPath: /var/jenkins_home
#          name: jenkins-home
#      volumes:
#      - name: jenkins-home
#        hostPath:
#          path: /var/jenkins_home
# [END jenkins_deployment]
# [START jenkins_service]
---
  kind: Service
  apiVersion: v1
  metadata:
    name: jenkins
  spec:
    type: LoadBalancer
    selector:
      app: jenkins
    ports:
      - name: jenkins
        protocol: TCP
        port: 8080
        targetPort: 8080
# [END jenkins_service]
# [START jenkins_service_slave]
---
  kind: Service
  apiVersion: v1
  metadata:
    name: jenkins-slave
  spec:
    selector:
      app: jenkins
    ports:
      - name: slave
        protocol: TCP
        port: 50000
        targetPort: 50000
# [END jenkins_service_slave]
