def label = "worker-${UUID.randomUUID().toString()}"

properties([
  buildDiscarder(logRotator(daysToKeepStr: "60", numToKeepStr: "10"))
])

podTemplate(label: label, containers: [
  containerTemplate(name: "executor", image: "$EXECUTOR_IMAGE", command: "cat", ttyEnabled: true)
],
volumes: [
  hostPathVolume(mountPath: "/var/run/docker.sock", hostPath: "/var/run/docker.sock")
]) {
  node(label) {
    stage("Checkout") {
      checkout([$class: "GitSCM",
        branches: [[name: "$BRANCH"]],
        doGenerateSubmoduleConfigurations: false,
        extensions: [],
        submoduleCfg: [],
        userRemoteConfigs: [[url: "$REPOSITORY_URL"]]]
      )
    }

    stage("Build Image") {
      container("executor") {
        sh "docker build -t $IMAGE_REPO/$IMAGE_NAME:$IMAGE_TAG ."
      }
    }

    stage("Push Image") {
      container("executor") {
        //sh "docker push $IMAGE_REPO/$IMAGE_NAME:$IMAGE_TAG"
        sh "gcloud docker -- push $IMAGE_REPO/$IMAGE_NAME:$IMAGE_TAG"
      }
    }
  }
}
