def label = "worker-${UUID.randomUUID().toString()}"
properties([
  buildDiscarder(logRotator(daysToKeepStr: "60", numToKeepStr: "10"))
])
podTemplate(label: label, containers: [
  containerTemplate(name: "docker", image: "docker", command: "cat", ttyEnabled: true),
  containerTemplate(name: "kubectl", image: "lachlanevenson/k8s-kubectl:latest", command: "cat", ttyEnabled: true),
  containerTemplate(name: "helm", image: "lachlanevenson/k8s-helm:latest", command: "cat", ttyEnabled: true)
],
volumes: [
  hostPathVolume(mountPath: "/var/run/docker.sock", hostPath: "/var/run/docker.sock")
]) {
  node(label) {
    stage("Info") {
      sh "uname -a"
    }
    stage("Run docker") {
      container("docker") {
        sh "docker images"
      }
    }
    stage("Run kubectl") {
      container("kubectl") {
        sh "kubectl get pod,svc"
      }
    }
    stage("Run helm") {
      container("helm") {
        sh "helm list"
      }
    }
  }
}
