def label = "worker-${UUID.randomUUID().toString()}"
properties([
  buildDiscarder(logRotator(daysToKeepStr: "60", numToKeepStr: "10"))
])
podTemplate(label: label, containers: [
  containerTemplate(name: "executor", image: "$EXECUTOR_IMAGE", command: "cat", ttyEnabled: true)
],
volumes: [
  hostPathVolume(mountPath: "/var/run/docker.sock", hostPath: "/var/run/docker.sock")
]) {
  node(label) {
    stage("Checkout") {
      checkout([$class: "GitSCM",
        branches: [[name: "$BRANCH"]],
        doGenerateSubmoduleConfigurations: false,
        extensions: [],
        submoduleCfg: [],
        userRemoteConfigs: [[url: "$REPOSITORY_URL"]]]
      )
    }
    stage("Test") {
      container("executor") {
        sh "mvn test"
      }
    }
    stage("Package") {
      container("executor") {
        sh "mvn package -DskipTests"
      }
    }
    stage("Result") {
      junit "**/target/surefire-reports/TEST-*.xml"
      archive "target/*.jar"
    }
  }
}
