def label = "worker-${UUID.randomUUID().toString()}"

podTemplate(label: label, containers: [
    containerTemplate(name: 'executor', image: '$EXECUTOR_IMAGE', command: 'cat', ttyEnabled: true)
  ]) {
  node(label) {
    stage('Checkout') {
      checkout([$class: 'GitSCM',
        branches: [[name: '$BRANCH']],
        doGenerateSubmoduleConfigurations: false,
        extensions: [],
        submoduleCfg: [],
        userRemoteConfigs: [[url: '$REPOSITORY_URL']]]
      )
    }

    stage('Build Image') {
      container('executor') {
        sh 'docker build -t $IMAGE_REPO:$IMAGE_TAG .'
      }
    }

    stage('Push Image') {
      container('executor') {
        sh 'docker push $IMAGE_REPO:$IMAGE_TAG'
      }
    }
  }
}
